openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/jm-root/bank/4.0.0
info:
  version: "4.0.0"
  title: jm-bank-api
  description: 银行API
paths:
  /bank/query:
    get:
      description: 查询余额
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string
        - name: ctCode
          in: query
          schema:
            type: string
      responses:
        '200':
          description: 查询结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResult'
  /bank/transfer:
    post:
      description: 转账
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferInfo'
      responses:
        '200':
          description: 转账结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferResult'
components:
  schemas:
    TransferInfo:
      type: object
      properties:
        fromUserId:
          type: string
          description: 转出用户Id
        toUserId:
          type: string
          description: 转入用户Id
        ctCode:
          type: string
          description: 货币编码
        amount:
          type: integer
          format: int64
          description: 交易额度
        allAmount:
          type: integer
          format: int32
          description: 是否转出所有余额
        memo:
          type: string
          description: 备注信息
        orderId:
          type: string
          description: 关联订单Id
    TransferResult:
      type: object
      properties:
        amount:
          type: integer
          format: int64
          description: 交易额度
        memo:
          type: string
          description: 备注信息
        orderId:
          type: string
          description: 关联订单Id
        ctId:
          type: integer
          format: int32
          description: 货币Id
        ctCode:
          type: string
          description: 货币编码
        crtime:
          type: string
          format: date-time
          description: 交易时间
        fromUserId:
          type: string
          description: 转出用户Id
        fromAccountBalance:
          type: integer
          format: int64
          description: 转出用户余额
        toUserId:
          type: string
          description: 转入用户Id
        toAccountBalance:
          type: integer
          format: int64
          description: 转出用户余额
    BalanceResult:
      type: object
